project_id = "oqngrwevaazcxeotyrdg"

[functions.get-exchange-rates]
verify_jwt = false

[functions.process-financial-file]
verify_jwt = false

[functions.check-data-integrity]
verify_jwt = false

[functions.process-investment-file]
verify_jwt = false

[functions.process-import]
verify_jwt = false

[functions.fix-categorization]
verify_jwt = false
